// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticalExam.Database_Context;

#nullable disable

namespace PracticalExam.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20230510012425_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PracticalExam.Database_Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblBook");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "G B Shaw",
                            BookName = "Man and Superman",
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Author = "Franz Kalka",
                            BookName = "The Castle",
                            Date = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            Author = "Guy the Manupassaul",
                            BookName = "A Woman's Life",
                            Date = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jibanananda Das",
                            BookName = "Bela Obela Kolbela",
                            Date = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            Author = "Julian Barnes",
                            BookName = "The Sense of an Ending",
                            Date = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
